language: bash
arch: ppc64le
addons:
  apt:
    packages:
    - cargo
rust: nightly
before_script:
- curl https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
- source ~/.nvm/nvm.sh
- nvm install 10
jobs:
  include:
    - arch: ppc64le
      script: sh ./build/build_ppc.sh
    - arch: s390x
      script: sh ./build/build_s390x.sh      
deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: XnzQ7WWlwrJWeoQb6xQUNWh/XLw6TljTdT5vAEkiYwoeqhAFS6LXrSd5VCVs3KOausmcvtGbn2p1TX4RXqSf/hTP82acxNs2uEcsa8yHYE8uNuX3ygu32uDFfupFFO/ZhvgJbAV3AOmsa5f80THYC2Wb0kbB7/LO0Ur45YRBpuw2nd2R8aS4LmVKMsKqg6AfDCXRxjqfB6iTgX/91Bl0TyAX14M0ckn40Y809WcEIDBx1TErmI55ulSthKWhu5j3MYQfmktOiqUOemKf4GEfb45GKWeBsthXD+gYX38W1E3ZN/ohtSgV1r9Z9hh9ZRnQvqnDmifHST293jOJ15J/Wp7+8WpuPQ4rV87b8wyNryQ74tjyAmN/Tcw7NxEpesAb+AWJzNW5R3AH9CgoHI8rq6fpWqPPW42Vhv+31XLK06Aocg9nFNXdLqjze6xoawod/VefAcLPTV0FXgZuVllB/zkOa5YWUCXewubH00o+DB7KynRDdeitJmeRo2xe/JPwpPsZkNrv/2bMlLwByunexb9kFExC861ETXY1NNrMe1YRbWCy/0+tMpYoqwPFxZq8xlU+ogEB6z5l/kqm8DsSKuvVdBwll6Rbg2puDn0BAK9dYmXBAHgPP+7uOTPlOssLzMZuYJ8SVyyiFfqPav7yf0H1t34yGZr1/K6aozi/Jd4=
  file: "/home/travis/ripgrep/*.tar.gz"
  on:
    repo: Siddhesh-Ghadi/ripgrep-prebuilt
    tags: true


